spring:
  datasource:
    url: jdbc:h2:mem:saegil_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
server:
  port: 8080
token:
  jwt:
    access-key: ThisIsLocalAccessKeyThisIsLocalAccessKey
    refresh-key: ThisIsLocalRefreshKeyThisIsLocalRefreshKey
    access-expired-hours: 1 # 1시간
    refresh-expired-hours: 336  # 14일
