spring:
  datasource:
    url: jdbc:h2:mem:saegil_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        use_sql_comments: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
token:
  jwt:
    access-key: ThisIsLocalAccessKeyThisIsLocalAccessKey
    refresh-key: ThisIsLocalRefreshKeyThisIsLocalRefreshKey
    access-expired-hours: 1 # 1시간
    refresh-expired-hours: 336  # 14일
oauth2:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    client_secret: ${KAKAO_CLIENT_SECRET}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    scope: ${KAKAO_SCOPE}
